[theme]
base = "light"
# Zurich Blue - Primary accent color
primaryColor = "#ff6b6b"
# Main background (white)
backgroundColor = "#ffffff"
# Panels / widget containers (light grey)
secondaryBackgroundColor = "#f0f2f6"
# Standard text color (dark grey)
textColor = "#262730"
# Global font family (falls back to system sans-serif)
font = "sans serif"

# You can keep adding other non-theme settings here, e.g.
[server]
# Uncomment to enable headless mode
headless = true
port = 8501

[browser]
# Use a larger timeout for data loading
serverTimeout = 300
gatherUsageStats = false

[mapbox]
# Replace with your actual token if using custom mapbox styles
# token = "" 