# Streamlit Secrets Configuration
# Diese Datei sollte in Streamlit Cloud in den "Secrets" Einstellungen konfiguriert werden

# API Configuration für Production
# Setze diese URL auf deine deployed FastAPI Backend URL

# WICHTIG: Für Streamlit Cloud Deployment diese URL in den Secrets konfigurieren:
STREAMLIT_API_URL = "https://vdss-4ovd.onrender.com"

# Alternative URLs (als Kommentar für Referenz):
# STREAMLIT_API_URL = "https://your-backend-url.herokuapp.com"  # Beispiel Heroku
# STREAMLIT_API_URL = "https://your-backend-url.railway.app"    # Beispiel Railway

# Lokale Entwicklung (Standard-Fallback ist bereits in config.py definiert)
# STREAMLIT_API_URL = "http://localhost:8000" 